/**
 * Law demo – mock data and i18n. Self-contained, no dependency on shared demo.
 * Keys: law_lang, law_state, law_active_tab
 */
(function (global) {
  var CONTACT_HR = 'https://www.mangai.hr/#contact';
  var CONTACT_EN = 'https://www.mangai.hr/en/#contact';

  var strings = {
    hr: {
      disclaimer: 'Napomena: Ovo nije pravni savjet. Demo služi za osnovnu kvalifikaciju i dogovor konzultacija.',
      footerTheme: 'Napomena: Tema i boje su potpuno prilagodljive vašem brendu.',
      heroTitle: 'AI demo za odvjetničke urede',
      heroSubtitle: 'Intake i kvalifikacija klijenata, inbox upita i automatizacija follow-upa – bez pravnog savjeta.',
      contact: 'Kontakt',
      backToDemo: 'Natrag na demo',
      demoMode: 'Demo način',
      langHr: 'HR',
      langEn: 'EN',
      integrationTitle: 'Integracija dostupna u sklopu proizvoda',
      integrationBody: 'Ova integracija se aktivira nakon implementacije. Želiš da ti pokažemo kako radi na tvom primjeru?',
      integrationCta: 'Pošalji upit',
      modalClose: 'Zatvori',
      tabOverview: 'Pregled',
      tabInbox: 'Inbox',
      tabClients: 'Klijenti',
      tabCases: 'Slučajevi',
      tabDocuments: 'Dokumenti',
      tabDeadlines: 'Rokovi',
      tabAutomations: 'Automatizacije',
      tabSettings: 'Postavke',
      kpiActiveCases: 'Aktivni slučajevi',
      kpiNewInquiries: 'Novi upiti (7 dana)',
      kpiDeadlinesWeek: 'Rokovi ovaj tjedan',
      kpiDocsInPrep: 'Dokumenti u pripremi',
      tagHitno: 'Hitno',
      tagStandard: 'Standard',
      actionConvertToCase: 'Pretvori u slučaj',
      quickRepliesTitle: 'Predlošci odgovora',
      quickReply1: 'Hvala, javit ću se uskoro.',
      quickReply2: 'Možemo dogovoriti termin za razgovor.',
      quickReply3: 'Evo dodatnih informacija koje ste tražili.',
      clientColName: 'Ime',
      clientColType: 'Tip',
      clientColContact: 'Kontakt',
      clientColStatus: 'Status',
      clientTypePhysical: 'Fizička osoba',
      clientTypeLegal: 'Pravna osoba',
      clientLinkedCases: 'Povezani slučajevi',
      clientRecentDocs: 'Nedavni dokumenti',
      caseColVrsta: 'Vrsta',
      caseColFaza: 'Faza',
      caseColPrioritet: 'Prioritet',
      caseColClient: 'Klijent',
      caseColActivity: 'Zadnja aktivnost',
      casePhaseNew: 'Novi',
      casePhaseActive: 'Aktivan',
      casePhaseWaiting: 'Na čekanju',
      casePhaseClosed: 'Zatvoren',
      caseAddNote: 'Dodaj bilješku',
      caseChangePhase: 'Promijeni fazu',
      caseNotesPlaceholder: 'Dodaj bilješku...',
      docColName: 'Naziv',
      docColTag: 'Tag',
      docColCase: 'Povezan slučaj',
      docColStatus: 'Status',
      docTagContract: 'Ugovor',
      docTagSubmission: 'Podnesak',
      docTagPowerOfAttorney: 'Punomoć',
      docStatusDraft: 'Nacrt',
      docStatusSent: 'Poslano',
      docStatusSigned: 'Potpisano',
      docActionGenerate: 'Generiraj nacrt',
      docActionMarkSent: 'Označi kao poslano',
      docActionMarkSigned: 'Označi kao potpisano',
      docDraftPreview: 'Pregled nacrta',
      docDraftLabel: 'Nacrt dokumenta (demo)',
      deadlineColDate: 'Datum',
      deadlineColCase: 'Slučaj',
      deadlineColTask: 'Zadatak',
      deadlineColStatus: 'Status',
      deadlineActionDone: 'Označi riješeno',
      deadlineActionSnooze: 'Odgodi 7 dana',
      automReminders: 'Podsjetnik za rokove',
      automFollowup: 'Auto follow-up klijentu',
      automDocuments: 'Prikupljanje dokumenata',
      automEmailSummary: 'Sažetak upita u email',
      automTagging: 'Tagiranje slučajeva po vrsti',
      integrationCalendar: 'Google Calendar',
      integrationWhatsApp: 'WhatsApp',
      integrationsTitle: 'Integracije',
      noClients: 'Nema klijenata',
      noCases: 'Nema slučajeva',
      noDocuments: 'Nema dokumenata',
      noDeadlines: 'Nema rokova',
      selectClient: 'Odaberi klijenta',
      selectCase: 'Odaberi slučaj',
      featClientsTitle: 'Klijenti i slučajevi',
      featClientsBullet1: 'Upravljanje klijentima i slučajevima',
      featClientsBullet2: 'Bilješke i faze',
      featInboxTitle: 'Inbox upita',
      featInboxBullet1: 'Upiti sortirani po prioritetu (Hitno/Standard)',
      featInboxBullet2: 'Brzi odgovori i pretvaranje u slučaj',
      featDocsTitle: 'Dokumenti i rokovi',
      featDocsBullet1: 'Dokumenti po statusu',
      featDocsBullet2: 'Rokovi s akcijama',
      featAutomTitle: 'Automatizacije',
      featAutomBullet1: 'Podsjetnici i prikupljanje dokumenata',
      featAutomBullet2: 'Sažetak upita u email',
      featClientsCta: 'Pogledaj klijente',
      featInboxCta: 'Otvori inbox',
      featDocsCta: 'Pogledaj dokumente',
      featAutomCta: 'Uključi automatizacije',
      landingDisclaimer: 'Demo prikazuje osnovni koncept.\nFinalna verzija se razvija prema vašim procesima, integracijama i vizualnom identitetu.',
      demoDisclaimer: 'Demo prikazuje osnovni koncept.\nFinalna verzija se razvija prema vašim procesima, integracijama i vizualnom identitetu.',
    },
    en: {
      disclaimer: 'Note: This is not legal advice. The demo is for initial qualification and booking consultations.',
      footerTheme: 'Note: The theme and UI colors are fully customizable to your brand.',
      heroTitle: 'AI demo for law firms',
      heroSubtitle: 'Client intake and qualification, inquiry inbox and follow-up automation – not legal advice.',
      contact: 'Contact',
      backToDemo: 'Back to demo',
      demoMode: 'Demo mode',
      langHr: 'HR',
      langEn: 'EN',
      integrationTitle: 'Integration available in the product',
      integrationBody: 'This integration is enabled during implementation. Want to see it on your use case?',
      integrationCta: 'Send inquiry',
      modalClose: 'Close',
      tabOverview: 'Overview',
      tabInbox: 'Inbox',
      tabClients: 'Clients',
      tabCases: 'Cases',
      tabDocuments: 'Documents',
      tabDeadlines: 'Deadlines',
      tabAutomations: 'Automations',
      tabSettings: 'Settings',
      kpiActiveCases: 'Active cases',
      kpiNewInquiries: 'New inquiries (7 days)',
      kpiDeadlinesWeek: 'Deadlines this week',
      kpiDocsInPrep: 'Documents in preparation',
      tagHitno: 'Urgent',
      tagStandard: 'Standard',
      actionConvertToCase: 'Convert to case',
      quickRepliesTitle: 'Reply templates',
      quickReply1: 'Thanks, I\'ll get back to you soon.',
      quickReply2: 'We can schedule a call to discuss.',
      quickReply3: 'Here\'s the additional info you asked for.',
      clientColName: 'Name',
      clientColType: 'Type',
      clientColContact: 'Contact',
      clientColStatus: 'Status',
      clientTypePhysical: 'Individual',
      clientTypeLegal: 'Legal entity',
      clientLinkedCases: 'Linked cases',
      clientRecentDocs: 'Recent documents',
      caseColVrsta: 'Type',
      caseColFaza: 'Phase',
      caseColPrioritet: 'Priority',
      caseColClient: 'Client',
      caseColActivity: 'Last activity',
      casePhaseNew: 'New',
      casePhaseActive: 'Active',
      casePhaseWaiting: 'Waiting',
      casePhaseClosed: 'Closed',
      caseAddNote: 'Add note',
      caseChangePhase: 'Change phase',
      caseNotesPlaceholder: 'Add note...',
      docColName: 'Name',
      docColTag: 'Tag',
      docColCase: 'Linked case',
      docColStatus: 'Status',
      docTagContract: 'Contract',
      docTagSubmission: 'Submission',
      docTagPowerOfAttorney: 'Power of attorney',
      docStatusDraft: 'Draft',
      docStatusSent: 'Sent',
      docStatusSigned: 'Signed',
      docActionGenerate: 'Generate draft',
      docActionMarkSent: 'Mark as sent',
      docActionMarkSigned: 'Mark as signed',
      docDraftPreview: 'Draft preview',
      docDraftLabel: 'Document draft (demo)',
      deadlineColDate: 'Date',
      deadlineColCase: 'Case',
      deadlineColTask: 'Task',
      deadlineColStatus: 'Status',
      deadlineActionDone: 'Mark done',
      deadlineActionSnooze: 'Snooze 7 days',
      automReminders: 'Deadline reminders',
      automFollowup: 'Auto follow-up to client',
      automDocuments: 'Document collection',
      automEmailSummary: 'Inquiry summary in email',
      automTagging: 'Case tagging by type',
      integrationCalendar: 'Google Calendar',
      integrationWhatsApp: 'WhatsApp',
      integrationsTitle: 'Integrations',
      noClients: 'No clients',
      noCases: 'No cases',
      noDocuments: 'No documents',
      noDeadlines: 'No deadlines',
      selectClient: 'Select client',
      selectCase: 'Select case',
      featClientsTitle: 'Clients & cases',
      featClientsBullet1: 'Manage clients and cases',
      featClientsBullet2: 'Notes and phases',
      featInboxTitle: 'Inquiry inbox',
      featInboxBullet1: 'Prioritized inquiries (Urgent/Standard)',
      featInboxBullet2: 'Quick replies and convert to case',
      featDocsTitle: 'Documents & deadlines',
      featDocsBullet1: 'Documents by status',
      featDocsBullet2: 'Deadlines with actions',
      featAutomTitle: 'Automations',
      featAutomBullet1: 'Reminders and document collection',
      featAutomBullet2: 'Inquiry summary in email',
      featClientsCta: 'View clients',
      featInboxCta: 'Open inbox',
      featDocsCta: 'View documents',
      featAutomCta: 'Enable automations',
      landingDisclaimer: 'The demo presents the core concept.\nThe final version is developed according to your workflows, integrations, and visual identity.',
      demoDisclaimer: 'The demo presents the core concept.\nThe final version is developed according to your workflows, integrations, and visual identity.',
    },
  };

  var data = {
    kpis: [
      { value: 8, labelKey: 'kpiActiveCases' },
      { value: 9, labelKey: 'kpiNewInquiries' },
      { value: 5, labelKey: 'kpiDeadlinesWeek' },
      { value: 4, labelKey: 'kpiDocsInPrep' },
    ],
    inbox: [
      { id: 1, name: 'Ante M.', preview: 'Potreban mi je savjet za raskid ugovora...', time: '10 min', unread: true, tag: 'hitno' },
      { id: 2, name: 'Marija S.', preview: 'Nasljedstvo – što trebam donijeti na konzultaciju?', time: '30 min', unread: true, tag: 'standard' },
      { id: 3, name: 'Igor K.', preview: 'Oštećenje na stanu – tko snosi troškove?', time: '1h', unread: false, tag: 'hitno' },
      { id: 4, name: 'Jelena P.', preview: 'Radni spor – mogu li dobiti termin?', time: '3h', unread: false, tag: 'hitno' },
      { id: 5, name: 'Krešimir L.', preview: 'Osnivanje d.o.o. – koraci i cijena...', time: '1d', unread: true, tag: 'standard' },
      { id: 6, name: 'Sanja D.', preview: 'Razvod – dogovoreni uvjeti...', time: '1d', unread: false, tag: 'standard' },
      { id: 7, name: 'Bruno V.', preview: 'Potraživanje od dužnika...', time: '2d', unread: false, tag: 'hitno' },
      { id: 8, name: 'Tina F.', preview: 'Pregled ugovora prije potpisa...', time: '2d', unread: true, tag: 'standard' },
    ],
    clients: [
      { id: 1, name: 'Ante Marković', tip: 'fizicka', kontakt: 'ante@email.hr', status: 'aktivan', caseIds: [1], docIds: [1] },
      { id: 2, name: 'Marija Šimić', tip: 'fizicka', kontakt: 'marija.s@email.hr', status: 'aktivan', caseIds: [2], docIds: [2] },
      { id: 3, name: 'Igor Kovač', tip: 'fizicka', kontakt: 'igor.k@gmail.com', status: 'aktivan', caseIds: [3], docIds: [3, 11] },
      { id: 4, name: 'Jelena Perić', tip: 'fizicka', kontakt: '+385 91 123 4567', status: 'aktivan', caseIds: [4], docIds: [4] },
      { id: 5, name: 'TechVision d.o.o.', tip: 'pravna', kontakt: 'info@techvision.hr', status: 'aktivan', caseIds: [5], docIds: [5, 12] },
      { id: 6, name: 'Sanja Dragić', tip: 'fizicka', kontakt: 'sanja.d@email.hr', status: 'aktivan', caseIds: [6], docIds: [6] },
      { id: 7, name: 'Bruno Vuković', tip: 'fizicka', kontakt: 'bruno.v@gmail.com', status: 'aktivan', caseIds: [7], docIds: [7] },
      { id: 8, name: 'Tina Franić', tip: 'fizicka', kontakt: '+385 98 765 4321', status: 'aktivan', caseIds: [8], docIds: [8] },
      { id: 9, name: 'Luka Belić', tip: 'fizicka', kontakt: 'luka.b@email.hr', status: 'neaktivan', caseIds: [9], docIds: [9] },
      { id: 10, name: 'Invest Group j.d.o.o.', tip: 'pravna', kontakt: 'legal@investgroup.hr', status: 'aktivan', caseIds: [], docIds: [] },
      { id: 11, name: 'Davor Kralj', tip: 'fizicka', kontakt: 'davor.k@email.hr', status: 'aktivan', caseIds: [], docIds: [] },
      { id: 12, name: 'Martina Babić', tip: 'fizicka', kontakt: 'martina.b@gmail.com', status: 'aktivan', caseIds: [10], docIds: [10] },
    ],
    cases: [
      { id: 1, vrsta: 'ugovorno', faza: 'active', prioritet: 'visok', klijentId: 1, klijent: 'Ante Marković', zadnjaAktivnost: '28.1.2026' },
      { id: 2, vrsta: 'nasljedstvo', faza: 'active', prioritet: 'srednji', klijentId: 2, klijent: 'Marija Šimić', zadnjaAktivnost: '29.1.2026' },
      { id: 3, vrsta: 'imovinsko', faza: 'waiting', prioritet: 'visok', klijentId: 3, klijent: 'Igor Kovač', zadnjaAktivnost: '27.1.2026' },
      { id: 4, vrsta: 'radno', faza: 'new', prioritet: 'hitno', klijentId: 4, klijent: 'Jelena Perić', zadnjaAktivnost: '30.1.2026' },
      { id: 5, vrsta: 'tvrrtko', faza: 'active', prioritet: 'srednji', klijentId: 5, klijent: 'TechVision d.o.o.', zadnjaAktivnost: '29.1.2026' },
      { id: 6, vrsta: 'obiteljsko', faza: 'active', prioritet: 'srednji', klijentId: 6, klijent: 'Sanja Dragić', zadnjaAktivnost: '28.1.2026' },
      { id: 7, vrsta: 'potrazivanje', faza: 'waiting', prioritet: 'visok', klijentId: 7, klijent: 'Bruno Vuković', zadnjaAktivnost: '26.1.2026' },
      { id: 8, vrsta: 'ugovorno', faza: 'active', prioritet: 'srednji', klijentId: 8, klijent: 'Tina Franić', zadnjaAktivnost: '30.1.2026' },
      { id: 9, vrsta: 'upravno', faza: 'closed', prioritet: 'srednji', klijentId: 9, klijent: 'Luka Belić', zadnjaAktivnost: '15.1.2026' },
      { id: 10, vrsta: 'imovinsko', faza: 'new', prioritet: 'srednji', klijentId: 12, klijent: 'Martina Babić', zadnjaAktivnost: '31.1.2026' },
    ],
    documents: [
      { id: 1, naziv: 'Ugovor o raskidu – Ante M.', tag: 'ugovor', slucajId: 1, slucaj: 'Raskid ugovora', status: 'draft' },
      { id: 2, naziv: 'Zahtjev za nasljedstvo – Marija S.', tag: 'podnesak', slucajId: 2, slucaj: 'Nasljedstvo', status: 'sent' },
      { id: 3, naziv: 'Tužba – oštećenje stana', tag: 'podnesak', slucajId: 3, slucaj: 'Oštećenje stana', status: 'draft' },
      { id: 4, naziv: 'Punomoć – Jelena P.', tag: 'punomoc', slucajId: 4, slucaj: 'Radni spor', status: 'signed' },
      { id: 5, naziv: 'Osvježenje d.o.o. – osnivački ugovor', tag: 'ugovor', slucajId: 5, slucaj: 'Osnivanje d.o.o.', status: 'draft' },
      { id: 6, naziv: 'Sporazum o razvodu – Sanja D.', tag: 'ugovor', slucajId: 6, slucaj: 'Razvod', status: 'sent' },
      { id: 7, naziv: 'Opoziv – potraživanje Bruno V.', tag: 'podnesak', slucajId: 7, slucaj: 'Potraživanje', status: 'draft' },
      { id: 8, naziv: 'Ugovor o kupoprodaji – Tina F.', tag: 'ugovor', slucajId: 8, slucaj: 'Pregled ugovora', status: 'signed' },
      { id: 9, naziv: 'Žalba – Luka B.', tag: 'podnesak', slucajId: 9, slucaj: 'Žalba na odluku', status: 'sent' },
      { id: 10, naziv: 'Punomoć za zastupanje – Martina B.', tag: 'punomoc', slucajId: 10, slucaj: 'Kupoprodaja stana', status: 'draft' },
      { id: 11, naziv: 'Naknada štete – Igor K.', tag: 'podnesak', slucajId: 3, slucaj: 'Oštećenje stana', status: 'draft' },
      { id: 12, naziv: 'Ugovor o angažmanu – TechVision', tag: 'ugovor', slucajId: 5, slucaj: 'Osnivanje d.o.o.', status: 'sent' },
    ],
    deadlines: [
      { id: 1, datum: '3.2.2026', slucajId: 1, slucaj: 'Raskid ugovora', zadatak: 'Rok za odgovor tuženiku', dodijeljeno: 'Odvjetnik', status: 'pending' },
      { id: 2, datum: '5.2.2026', slucajId: 2, slucaj: 'Nasljedstvo', zadatak: 'Predaja dokumentacije na sud', dodijeljeno: 'Odvjetnik', status: 'pending' },
      { id: 3, datum: '7.2.2026', slucajId: 4, slucaj: 'Radni spor', zadatak: 'Rok žalbe na odluku', dodijeljeno: 'Odvjetnik', status: 'pending' },
      { id: 4, datum: '10.2.2026', slucajId: 3, slucaj: 'Oštećenje stana', zadatak: 'Podsjetnik – čekanje odgovora suda', dodijeljeno: 'Paralegal', status: 'pending' },
      { id: 5, datum: '12.2.2026', slucajId: 5, slucaj: 'Osnivanje d.o.o.', zadatak: 'Registracija u sudski register', dodijeljeno: 'Odvjetnik', status: 'pending' },
      { id: 6, datum: '15.2.2026', slucajId: 6, slucaj: 'Razvod', zadatak: 'Rok za predaju sporazuma', dodijeljeno: 'Odvjetnik', status: 'pending' },
      { id: 7, datum: '18.2.2026', slucajId: 7, slucaj: 'Potraživanje', zadatak: 'Podsjetnik – sljedeći korak', dodijeljeno: 'Paralegal', status: 'pending' },
      { id: 8, datum: '20.2.2026', slucajId: 8, slucaj: 'Pregled ugovora', zadatak: 'Potvrda potpisa – Tina F.', dodijeljeno: 'Odvjetnik', status: 'pending' },
    ],
    automations: [
      { key: 'reminders', labelKey: 'automReminders' },
      { key: 'followup', labelKey: 'automFollowup' },
      { key: 'documents', labelKey: 'automDocuments' },
      { key: 'emailSummary', labelKey: 'automEmailSummary' },
      { key: 'tagging', labelKey: 'automTagging' },
    ],
  };

  function getLang() {
    try {
      var stored = localStorage.getItem('law_lang');
      if (stored === 'en' || stored === 'hr') return stored;
    } catch (e) {}
    return 'hr';
  }

  function setLang(lang) {
    try {
      localStorage.setItem('law_lang', lang);
    } catch (e) {}
  }

  function tr(key, lang) {
    lang = lang || getLang();
    return (strings[lang] && strings[lang][key]) || (strings.hr && strings.hr[key]) || key;
  }

  function getContactUrl(lang) {
    return (lang || getLang()) === 'en' ? CONTACT_EN : CONTACT_HR;
  }

  global.LawData = {
    strings: strings,
    tr: tr,
    data: data,
    getLang: getLang,
    setLang: setLang,
    getContactUrl: getContactUrl,
    CONTACT_HR: CONTACT_HR,
    CONTACT_EN: CONTACT_EN,
  };
})(typeof window !== 'undefined' ? window : this);
