/**
 * Demo mock data per vertical: KPIs, inbox threads, leads, bookings (salon + ordinacija).
 * Status keys: new, qualified, booked, closed – translate in UI via i18n.
 * KPI label keys are in i18n (kpi1, kpi2, kpi3, kpi4 per vertical); values here.
 */
(function (global) {
  var statusKeys = ['new', 'qualified', 'booked', 'closed'];

  var kpiLabels = {
    nekretnine: { kpi1: 'Upiti ovaj tjedan', kpi2: 'Kvalificirani leadovi', kpi3: 'Zakazani razgledi', kpi4: 'Prosječno vrijeme odgovora' },
    salon: { kpi1: 'Rezervacije ovaj tjedan', kpi2: 'Novi upiti', kpi3: 'No-show %', kpi4: 'Zauzetost termina' },
    agencija: { kpi1: 'Novi leadovi', kpi2: 'Kvalificirani', kpi3: 'Zakazani sastanci', kpi4: 'Odgovoreno u 24h' },
    odvjetnik: { kpi1: 'Upiti ovaj tjedan', kpi2: 'Intake dovršen', kpi3: 'Zakazane konzultacije', kpi4: 'Prosječno vrijeme odgovora' },
    ordinacija: { kpi1: 'Naručeni pacijenti', kpi2: 'Novi upiti', kpi3: 'No-show %', kpi4: 'Zauzetost termina' },
  };

  var kpiLabelsEn = {
    nekretnine: { kpi1: 'Inquiries this week', kpi2: 'Qualified leads', kpi3: 'Viewings scheduled', kpi4: 'Avg. response time' },
    salon: { kpi1: 'Bookings this week', kpi2: 'New inquiries', kpi3: 'No-show %', kpi4: 'Slot occupancy' },
    agencija: { kpi1: 'New leads', kpi2: 'Qualified', kpi3: 'Meetings scheduled', kpi4: 'Replied in 24h' },
    odvjetnik: { kpi1: 'Inquiries this week', kpi2: 'Intake completed', kpi3: 'Consultations scheduled', kpi4: 'Avg. response time' },
    ordinacija: { kpi1: 'Patients booked', kpi2: 'New inquiries', kpi3: 'No-show %', kpi4: 'Slot occupancy' },
  };

  function getKpiLabels(vertical, lang) {
    var map = lang === 'en' ? kpiLabelsEn : kpiLabels;
    return map[vertical] || map.nekretnine;
  }

  var data = {
    nekretnine: {
      kpis: [
        { value: 24, suffix: '' },
        { value: 12, suffix: '' },
        { value: 8, suffix: '' },
        { value: '2.4h', suffix: '' },
      ],
      inbox: [
        { id: 1, name: 'Ana Horvat', preview: 'Interesira me stan u centru, do 800€...', time: '10 min', unread: true },
        { id: 2, name: 'Marko Novak', preview: 'Tražim kuću za kupnju, Maksimir...', time: '1h', unread: true },
        { id: 3, name: 'Petra Kovač', preview: 'Hvala na informacijama, želimo razgled...', time: '2h', unread: false },
        { id: 4, name: 'Ivan Jurić', preview: 'Ima li još nekretnina u vašoj ponudi?', time: '5h', unread: false },
        { id: 5, name: 'Lucija Babić', preview: 'Budžet 1200€, 2 spavaće, Zagreb...', time: '1d', unread: true },
        { id: 6, name: 'Tomislav Marić', preview: 'Kada možemo dogovoriti razgled stana?', time: '1d', unread: false },
        { id: 7, name: 'Maja Šimić', preview: 'Tražim najam na dugi rok, 2+1...', time: '2d', unread: false },
        { id: 8, name: 'Filip Vuković', preview: 'Cijena za stan na Tratinskoj?', time: '2d', unread: true },
      ],
      leads: [
        { id: 1, name: 'Ana Horvat', purchaseRent: 'rent', locations: 'Centar Zagreb', budget: '800€', rooms: '2', status: 'new', nextStep: 'contact' },
        { id: 2, name: 'Marko Novak', purchaseRent: 'buy', locations: 'Maksimir, Trešnjevka', budget: '250.000€', rooms: '3+', status: 'qualified', nextStep: 'viewing' },
        { id: 3, name: 'Petra Kovač', purchaseRent: 'rent', locations: 'Novi Zagreb', budget: '750€', rooms: '2+1', status: 'qualified', nextStep: 'viewing' },
        { id: 4, name: 'Ivan Jurić', purchaseRent: 'buy', locations: 'Zapad Zagreb', budget: '180.000€', rooms: '2', status: 'new', nextStep: 'contact' },
        { id: 5, name: 'Lucija Babić', purchaseRent: 'rent', locations: 'Stenjevec, Trešnjevka', budget: '1200€', rooms: '2', status: 'qualified', nextStep: 'viewing' },
        { id: 6, name: 'Tomislav Marić', purchaseRent: 'rent', locations: 'Donji Grad', budget: '900€', rooms: '2', status: 'qualified', nextStep: 'viewing' },
        { id: 7, name: 'Maja Šimić', purchaseRent: 'rent', locations: 'Črnomerec, Podsused', budget: '650€', rooms: '1+1', status: 'new', nextStep: 'contact' },
        { id: 8, name: 'Filip Vuković', purchaseRent: 'buy', locations: 'Tratinska', budget: '195.000€', rooms: '3', status: 'qualified', nextStep: 'viewing' },
        { id: 9, name: 'Kristina Lovrek', purchaseRent: 'buy', locations: 'Novi Zagreb', budget: '200.000€', rooms: '3', status: 'closed', nextStep: '-' },
        { id: 10, name: 'Davor Stanić', purchaseRent: 'rent', locations: 'Centar', budget: '1500€', rooms: 'poslovni', status: 'new', nextStep: 'contact' },
        { id: 11, name: 'Martina Belić', purchaseRent: 'buy', locations: 'Split, Centar', budget: '280.000€', rooms: '3+', status: 'qualified', nextStep: 'viewing' },
        { id: 12, name: 'Luka Horvat', purchaseRent: 'rent', locations: 'Rijeka', budget: '550€', rooms: '1', status: 'new', nextStep: 'contact' },
        { id: 13, name: 'Sandra Kovačević', purchaseRent: 'buy', locations: 'Osijek', budget: '120.000€', rooms: '2', status: 'qualified', nextStep: 'viewing' },
        { id: 14, name: 'Bruno Jurić', purchaseRent: 'rent', locations: 'Zagreb, Maksimir', budget: '700€', rooms: '2', status: 'new', nextStep: 'contact' },
        { id: 15, name: 'Elena Vuković', purchaseRent: 'buy', locations: 'Zadar, Stanovi', budget: '220.000€', rooms: '3', status: 'closed', nextStep: '-' },
      ],
      viewings: [
        { id: 1, dateTime: '5.2.2026 10:00', propertyId: 1, client: 'Petra Kovač', agent: 'Marina L.', status: 'scheduled' },
        { id: 2, dateTime: '5.2.2026 14:30', propertyId: 3, client: 'Marko Novak', agent: 'Marina L.', status: 'confirmed' },
        { id: 3, dateTime: '6.2.2026 09:00', propertyId: 2, client: 'Lucija Babić', agent: 'Ivan K.', status: 'scheduled' },
        { id: 4, dateTime: '6.2.2026 16:00', propertyId: 5, client: 'Tomislav Marić', agent: 'Ivan K.', status: 'done' },
        { id: 5, dateTime: '7.2.2026 11:00', propertyId: 4, client: 'Ivan Jurić', agent: 'Marina L.', status: 'confirmed' },
        { id: 6, dateTime: '7.2.2026 15:00', propertyId: 6, client: 'Filip Vuković', agent: 'Ivan K.', status: 'scheduled' },
        { id: 7, dateTime: '8.2.2026 10:00', propertyId: 1, client: 'Ana Horvat', agent: 'Marina L.', status: 'noshow' },
        { id: 8, dateTime: '8.2.2026 14:00', propertyId: 7, client: 'Martina Belić', agent: 'Ivan K.', status: 'scheduled' },
        { id: 9, dateTime: '9.2.2026 09:30', propertyId: 3, client: 'Sandra Kovačević', agent: 'Marina L.', status: 'confirmed' },
        { id: 10, dateTime: '9.2.2026 13:00', propertyId: 8, client: 'Bruno Jurić', agent: 'Ivan K.', status: 'scheduled' },
      ],
      properties: [
        { id: 1, name: 'Stan Centar, Ilica 45', location: 'Centar Zagreb', price: '850€/mj', type: 'Stan', status: 'active' },
        { id: 2, name: 'Novogradnja Novi Zagreb', location: 'Siget, Zagreb', price: '175.000€', type: 'Stan', status: 'active' },
        { id: 3, name: 'Kuća Maksimir', location: 'Maksimir, Zagreb', price: '320.000€', type: 'Kuća', status: 'active' },
        { id: 4, name: 'Stan Zapad', location: 'Stenjevec, Zagreb', price: '145.000€', type: 'Stan', status: 'active' },
        { id: 5, name: '2+1 Donji Grad', location: 'Donji Grad, Zagreb', price: '920€/mj', type: 'Stan', status: 'active' },
        { id: 6, name: 'Stan Tratinska', location: 'Tratinska, Zagreb', price: '195.000€', type: 'Stan', status: 'active' },
        { id: 7, name: 'Vila Split', location: 'Split, Centar', price: '380.000€', type: 'Kuća', status: 'active' },
        { id: 8, name: 'Stan Maksimir', location: 'Maksimir, Zagreb', price: '720€/mj', type: 'Stan', status: 'active' },
        { id: 9, name: 'Poslovni prostor Centar', location: 'Centar Zagreb', price: '1.400€/mj', type: 'Poslovni', status: 'active' },
        { id: 10, name: 'Stan Novi Zagreb prodan', location: 'Siget', price: '168.000€', type: 'Stan', status: 'sold' },
        { id: 11, name: '2+1 Trešnjevka', location: 'Trešnjevka, Zagreb', price: '680€/mj', type: 'Stan', status: 'rented' },
        { id: 12, name: 'Kuća Rijeka', location: 'Rijeka', price: '245.000€', type: 'Kuća', status: 'active' },
        { id: 13, name: 'Stan Osijek', location: 'Osijek', price: '95.000€', type: 'Stan', status: 'active' },
        { id: 14, name: 'Apartman Zadar', location: 'Zadar', price: '1.100€/mj', type: 'Stan', status: 'rented' },
      ],
      bookings: null,
    },
    salon: {
      kpis: [
        { value: 34, suffix: '' },
        { value: 18, suffix: '' },
        { value: 6, suffix: '%' },
        { value: 78, suffix: '%' },
      ],
      inbox: [
        { id: 1, name: 'Sara M.', preview: 'Mogu li rezervirati za srijedu u 14h?', time: '5 min', unread: true },
        { id: 2, name: 'Elena K.', preview: 'Koje usluge imate za nokte?', time: '20 min', unread: true },
        { id: 3, name: 'Laura P.', preview: 'Hvala, vidimo se u petak!', time: '1h', unread: false },
        { id: 4, name: 'Martina V.', preview: 'Želim promjenu termina na subotu.', time: '2h', unread: true },
        { id: 5, name: 'Ivana T.', preview: 'Cijena za piling lica?', time: '5h', unread: false },
        { id: 6, name: 'Nikolina B.', preview: 'Ima li slobodan termin sutra?', time: '1d', unread: false },
        { id: 7, name: 'Mia R.', preview: 'Prvi put kod vas – što preporučujete?', time: '1d', unread: true },
        { id: 8, name: 'Tea Z.', preview: 'Otkazujem rezervaciju za četvrtak.', time: '2d', unread: false },
      ],
      leads: [
        { id: 1, name: 'Sara M.', intent: 'Rezervacija', budget: '-', status: 'booked' },
        { id: 2, name: 'Elena K.', intent: 'Upit usluga', budget: '-', status: 'qualified' },
        { id: 3, name: 'Martina V.', intent: 'Promjena termina', budget: '-', status: 'new' },
        { id: 4, name: 'Mia R.', intent: 'Novi klijent', budget: '-', status: 'qualified' },
      ],
      bookings: [
        { id: 1, clientId: 1, client: 'Sara M.', service: 'Manikura + lak', date: '1.2.2026', dateLabel: 'Subota 1.2.', time: '09:00', staffId: 1, staff: 'Ana K.', status: 'pending' },
        { id: 2, clientId: 2, client: 'Elena K.', service: 'Pedikura', date: '1.2.2026', dateLabel: 'Subota 1.2.', time: '10:30', staffId: 2, staff: 'Maja L.', status: 'confirmed' },
        { id: 3, clientId: 3, client: 'Laura P.', service: 'Farbanje + šišanje', date: '1.2.2026', dateLabel: 'Subota 1.2.', time: '11:00', staffId: 1, staff: 'Ana K.', status: 'confirmed' },
        { id: 4, clientId: 4, client: 'Martina V.', service: 'Čišćenje lica', date: '1.2.2026', dateLabel: 'Subota 1.2.', time: '14:00', staffId: 3, staff: 'Petra M.', status: 'pending' },
        { id: 5, clientId: 5, client: 'Ivana T.', service: 'Piling + masaža lica', date: '2.2.2026', dateLabel: 'Nedjelja 2.2.', time: '10:00', staffId: 3, staff: 'Petra M.', status: 'pending' },
        { id: 6, clientId: 6, client: 'Nikolina B.', service: 'Manikura gel', date: '2.2.2026', dateLabel: 'Nedjelja 2.2.', time: '12:00', staffId: 2, staff: 'Maja L.', status: 'confirmed' },
        { id: 7, clientId: 7, client: 'Mia R.', service: 'Šišanje žensko', date: '3.2.2026', dateLabel: 'Ponedjeljak 3.2.', time: '09:30', staffId: 1, staff: 'Ana K.', status: 'pending' },
        { id: 8, clientId: 8, client: 'Tea Z.', service: 'Šišanje', date: '3.2.2026', dateLabel: 'Ponedjeljak 3.2.', time: '14:00', staffId: 1, staff: 'Ana K.', status: 'cancelled' },
        { id: 9, clientId: 1, client: 'Sara M.', service: 'Lak za nokte', date: '4.2.2026', dateLabel: 'Utorak 4.2.', time: '16:00', staffId: 2, staff: 'Maja L.', status: 'pending' },
        { id: 10, clientId: 9, client: 'Katarina S.', service: 'Farbanje', date: '4.2.2026', dateLabel: 'Utorak 4.2.', time: '10:00', staffId: 1, staff: 'Ana K.', status: 'confirmed' },
        { id: 11, clientId: 10, client: 'Lucija H.', service: 'Manikura + lak', date: '5.2.2026', dateLabel: 'Srijeda 5.2.', time: '11:00', staffId: 2, staff: 'Maja L.', status: 'pending' },
        { id: 12, clientId: 11, client: 'Dora N.', service: 'Čišćenje + maska', date: '5.2.2026', dateLabel: 'Srijeda 5.2.', time: '15:00', staffId: 3, staff: 'Petra M.', status: 'confirmed' },
        { id: 13, clientId: 12, client: 'Tina F.', service: 'Pedikura', date: '6.2.2026', dateLabel: 'Četvrtak 6.2.', time: '09:00', staffId: 2, staff: 'Maja L.', status: 'completed' },
        { id: 14, clientId: 13, client: 'Bruno J.', service: 'Šišanje muško', date: '6.2.2026', dateLabel: 'Četvrtak 6.2.', time: '17:00', staffId: 4, staff: 'Ivan P.', status: 'noshow' },
        { id: 15, clientId: 14, client: 'Andrea V.', service: 'Piling tijela', date: '7.2.2026', dateLabel: 'Petak 7.2.', time: '10:30', staffId: 3, staff: 'Petra M.', status: 'pending' },
        { id: 16, clientId: 15, client: 'Sanja K.', service: 'Farbanje + šišanje', date: '7.2.2026', dateLabel: 'Petak 7.2.', time: '14:00', staffId: 1, staff: 'Ana K.', status: 'confirmed' },
        { id: 17, clientId: 3, client: 'Laura P.', service: 'Manikura', date: '8.2.2026', dateLabel: 'Subota 8.2.', time: '11:00', staffId: 2, staff: 'Maja L.', status: 'pending' },
        { id: 18, clientId: 16, client: 'Kristina L.', service: 'Čišćenje lica', date: '10.2.2026', dateLabel: 'Ponedjeljak 10.2.', time: '09:00', staffId: 3, staff: 'Petra M.', status: 'pending' },
        { id: 19, clientId: 17, client: 'Maja Š.', service: 'Pedikura + lak', date: '15.2.2026', dateLabel: 'Subota 15.2.', time: '13:00', staffId: 2, staff: 'Maja L.', status: 'pending' },
        { id: 20, clientId: 18, client: 'Iva B.', service: 'Šišanje žensko', date: '20.2.2026', dateLabel: 'Četvrtak 20.2.', time: '16:00', staffId: 1, staff: 'Ana K.', status: 'pending' },
      ],
      clients: [
        { id: 1, name: 'Sara M.', lastVisit: '28.1.2026', visitCount: 12, preferredService: 'Manikura + lak' },
        { id: 2, name: 'Elena K.', lastVisit: '25.1.2026', visitCount: 8, preferredService: 'Pedikura' },
        { id: 3, name: 'Laura P.', lastVisit: '1.2.2026', visitCount: 24, preferredService: 'Farbanje + šišanje' },
        { id: 4, name: 'Martina V.', lastVisit: '20.1.2026', visitCount: 5, preferredService: 'Čišćenje lica' },
        { id: 5, name: 'Ivana T.', lastVisit: '15.1.2026', visitCount: 3, preferredService: 'Piling + masaža lica' },
        { id: 6, name: 'Nikolina B.', lastVisit: '28.1.2026', visitCount: 6, preferredService: 'Manikura gel' },
        { id: 7, name: 'Mia R.', lastVisit: null, visitCount: 0, preferredService: '-' },
        { id: 8, name: 'Tea Z.', lastVisit: '10.1.2026', visitCount: 14, preferredService: 'Šišanje' },
        { id: 9, name: 'Katarina S.', lastVisit: '22.1.2026', visitCount: 9, preferredService: 'Farbanje' },
        { id: 10, name: 'Lucija H.', lastVisit: '30.1.2026', visitCount: 7, preferredService: 'Manikura + lak' },
        { id: 11, name: 'Dora N.', lastVisit: '18.1.2026', visitCount: 4, preferredService: 'Čišćenje + maska' },
        { id: 12, name: 'Tina F.', lastVisit: '6.2.2026', visitCount: 11, preferredService: 'Pedikura' },
        { id: 13, name: 'Bruno J.', lastVisit: '15.12.2025', visitCount: 2, preferredService: 'Šišanje muško' },
        { id: 14, name: 'Andrea V.', lastVisit: '5.1.2026', visitCount: 6, preferredService: 'Piling tijela' },
        { id: 15, name: 'Sanja K.', lastVisit: '29.1.2026', visitCount: 18, preferredService: 'Farbanje + šišanje' },
        { id: 16, name: 'Kristina L.', lastVisit: '12.1.2026', visitCount: 5, preferredService: 'Čišćenje lica' },
        { id: 17, name: 'Maja Š.', lastVisit: '25.1.2026', visitCount: 8, preferredService: 'Pedikura + lak' },
        { id: 18, name: 'Iva B.', lastVisit: '20.1.2026', visitCount: 4, preferredService: 'Šišanje žensko' },
      ],
      services: [
        { id: 1, name: 'Manikura + lak', duration: '45 min', price: '120 kn', onlineBooking: true, popular: true },
        { id: 2, name: 'Pedikura', duration: '60 min', price: '150 kn', onlineBooking: true, popular: true },
        { id: 3, name: 'Farbanje + šišanje', duration: '120 min', price: '350 kn', onlineBooking: true, popular: true },
        { id: 4, name: 'Čišćenje lica', duration: '60 min', price: '180 kn', onlineBooking: true, popular: true },
        { id: 5, name: 'Piling + masaža lica', duration: '75 min', price: '220 kn', onlineBooking: false, popular: false },
        { id: 6, name: 'Manikura gel', duration: '60 min', price: '140 kn', onlineBooking: true, popular: true },
        { id: 7, name: 'Šišanje žensko', duration: '45 min', price: '100 kn', onlineBooking: true, popular: false },
        { id: 8, name: 'Šišanje muško', duration: '30 min', price: '70 kn', onlineBooking: true, popular: false },
        { id: 9, name: 'Farbanje', duration: '90 min', price: '280 kn', onlineBooking: true, popular: true },
        { id: 10, name: 'Čišćenje + maska', duration: '75 min', price: '200 kn', onlineBooking: true, popular: false },
        { id: 11, name: 'Piling tijela', duration: '90 min', price: '250 kn', onlineBooking: false, popular: false },
        { id: 12, name: 'Pedikura + lak', duration: '75 min', price: '170 kn', onlineBooking: true, popular: true },
      ],
      staff: [
        { id: 1, name: 'Ana K.', specialty: 'Šišanje, farbanje', workingHours: 'Pon–Sub 09:00–17:00', availability: ['09:00', '10:00', '11:00', '14:00', '15:00'] },
        { id: 2, name: 'Maja L.', specialty: 'Nokti, pedikura', workingHours: 'Pon–Sub 09:00–18:00', availability: ['09:00', '12:00', '13:00', '16:00'] },
        { id: 3, name: 'Petra M.', specialty: 'Kozmetika, tretmani', workingHours: 'Utor–Sub 10:00–16:00', availability: ['10:00', '11:00', '15:00'] },
        { id: 4, name: 'Ivan P.', specialty: 'Muško šišanje', workingHours: 'Čet–Sub 14:00–20:00', availability: ['17:00', '18:00'] },
        { id: 5, name: 'Lana T.', specialty: 'Nokti, manikura', workingHours: 'Pon–Pet 08:00–14:00', availability: ['08:00', '09:00'] },
        { id: 6, name: 'Marina S.', specialty: 'Farbanje', workingHours: 'Sri–Sub 10:00–18:00', availability: ['10:00', '14:00', '15:00'] },
      ],
    },
    agencija: {
      kpis: [
        { value: 19, suffix: '' },
        { value: 11, suffix: '' },
        { value: 6, suffix: '' },
        { value: 94, suffix: '%' },
      ],
      inbox: [
        { id: 1, name: 'Digital d.o.o.', preview: 'Treba nam kampanja za lansiranje proizvoda...', time: '15 min', unread: true },
        { id: 2, name: 'Startup XYZ', preview: 'Budžet za Q1 je 15k, želimo social + PPC...', time: '1h', unread: true },
        { id: 3, name: 'Brand Co', preview: 'Kada možemo imati kick-off sastanak?', time: '2h', unread: false },
        { id: 4, name: 'E-commerce HR', preview: 'Potreban nam je white-label chatbot...', time: '5h', unread: false },
        { id: 5, name: 'Tech Startup', preview: 'Lead gen + follow-up automatizacija...', time: '1d', unread: true },
        { id: 6, name: 'Fashion Brand', preview: 'Treba nam strategija za Instagram...', time: '1d', unread: false },
        { id: 7, name: 'Restaurant Group', preview: 'Lokalni marketing za 5 restorana...', time: '2d', unread: false },
        { id: 8, name: 'Fit Studio', preview: 'Kampanja za otvaranje novog studija...', time: '2d', unread: true },
      ],
      leads: [
        { id: 1, name: 'Digital d.o.o.', industry: 'Tech', budgetMin: 15, budgetMax: 25, services: 'ads,seo,content', urgency: 'high', status: 'new' },
        { id: 2, name: 'Startup XYZ', industry: 'SaaS', budgetMin: 10, budgetMax: 20, services: 'ads,seo', urgency: 'medium', status: 'qualified' },
        { id: 3, name: 'Brand Co', industry: 'Retail', budgetMin: 20, budgetMax: 40, services: 'ads,content', urgency: 'high', status: 'qualified' },
        { id: 4, name: 'E-commerce HR', industry: 'E-commerce', budgetMin: 20, budgetMax: 35, services: 'ads,seo,content', urgency: 'high', status: 'qualified' },
        { id: 5, name: 'Tech Startup', industry: 'Tech', budgetMin: 8, budgetMax: 15, services: 'ads', urgency: 'medium', status: 'new' },
        { id: 6, name: 'Fashion Brand', industry: 'Retail', budgetMin: 5, budgetMax: 12, services: 'ads,content', urgency: 'low', status: 'qualified' },
        { id: 7, name: 'Restaurant Group', industry: 'HoReCa', budgetMin: 8, budgetMax: 18, services: 'ads,content', urgency: 'medium', status: 'new' },
        { id: 8, name: 'Fit Studio', industry: 'Fitness', budgetMin: 3, budgetMax: 8, services: 'ads', urgency: 'high', status: 'closed' },
        { id: 9, name: 'MedLab d.o.o.', industry: 'Healthcare', budgetMin: 12, budgetMax: 22, services: 'seo,content', urgency: 'medium', status: 'new' },
        { id: 10, name: 'AutoPlus', industry: 'Automotive', budgetMin: 18, budgetMax: 30, services: 'ads,seo', urgency: 'high', status: 'info_requested' },
        { id: 11, name: 'GreenEnergy', industry: 'Energy', budgetMin: 25, budgetMax: 50, services: 'ads,seo,content', urgency: 'low', status: 'qualified' },
        { id: 12, name: 'EduPlatform', industry: 'EdTech', budgetMin: 10, budgetMax: 20, services: 'ads,content', urgency: 'medium', status: 'new' },
        { id: 13, name: 'FoodDelivery HR', industry: 'Food', budgetMin: 15, budgetMax: 28, services: 'ads', urgency: 'high', status: 'qualified' },
        { id: 14, name: 'BuildCorp', industry: 'Construction', budgetMin: 8, budgetMax: 15, services: 'seo,content', urgency: 'low', status: 'new' },
        { id: 15, name: 'TravelAgency', industry: 'Travel', budgetMin: 20, budgetMax: 45, services: 'ads,seo,content', urgency: 'high', status: 'qualified' },
      ],
      clients: [
        { id: 1, name: 'Digital d.o.o.', package: 'Premium', channels: 'Meta, Google, LinkedIn', status: 'active', spend: 4200, leads: 89, cpa: 47, note: 'Povećali budžet za Q2. A/B test na naslovima.' },
        { id: 2, name: 'Brand Co', package: 'Standard', channels: 'Meta, Google', status: 'active', spend: 2800, leads: 156, cpa: 18, note: 'Nova kampanja za lansiranje – kreative u izradi.' },
        { id: 3, name: 'E-commerce HR', package: 'Premium', channels: 'Google, Meta, TikTok', status: 'active', spend: 5100, leads: 234, cpa: 22, note: 'CPA ispod cilja. Razmisliti o skaliranju.' },
        { id: 4, name: 'Fashion Brand', package: 'Starter', channels: 'Meta, Instagram', status: 'active', spend: 1200, leads: 45, cpa: 27, note: 'Sezonska kampanja – rezultati solidni.' },
        { id: 5, name: 'Tech Startup', package: 'Standard', channels: 'LinkedIn, Google', status: 'active', spend: 1900, leads: 62, cpa: 31, note: 'Webinar kampanja – 12 prijava ovaj tjedan.' },
        { id: 6, name: 'Restaurant Group', package: 'Starter', channels: 'Meta, Google Maps', status: 'active', spend: 800, leads: 120, cpa: 7, note: 'Lokalni oglasi – dobar odziv u 3 lokacije.' },
        { id: 7, name: 'GreenEnergy', package: 'Premium', channels: 'Google, LinkedIn, Meta', status: 'active', spend: 3800, leads: 34, cpa: 112, note: 'B2B lead gen – kvaliteta leadova visoka.' },
        { id: 8, name: 'TravelAgency', package: 'Standard', channels: 'Meta, Google', status: 'active', spend: 3200, leads: 178, cpa: 18, note: 'Ljetna kampanja – booking konverzije +15%.' },
        { id: 9, name: 'MedLab d.o.o.', package: 'Standard', channels: 'Google, LinkedIn', status: 'paused', spend: 1500, leads: 28, cpa: 54, note: 'Kampanja pauzirana do odobrenja regulative.' },
        { id: 10, name: 'AutoPlus', package: 'Premium', channels: 'Google, Meta', status: 'active', spend: 4500, leads: 95, cpa: 47, note: 'Novi oglasi za model 2026 – čekamo odobrenje.' },
      ],
      campaigns: [
        { id: 1, name: 'Digital – Q1 Launch', channel: 'Meta', budget: 8000, status: 'active', lastModified: '28.1.2026' },
        { id: 2, name: 'Brand Co – Awareness', channel: 'Google', budget: 5000, status: 'active', lastModified: '29.1.2026' },
        { id: 3, name: 'E-commerce – Retargeting', channel: 'Meta', budget: 3500, status: 'active', lastModified: '30.1.2026' },
        { id: 4, name: 'Fashion – Spring', channel: 'Instagram', budget: 2000, status: 'paused', lastModified: '31.1.2026' },
        { id: 5, name: 'Tech Startup – LinkedIn', channel: 'LinkedIn', budget: 2500, status: 'active', lastModified: '1.2.2026' },
        { id: 6, name: 'Restaurant – Local', channel: 'Meta', budget: 1200, status: 'active', lastModified: '1.2.2026' },
        { id: 7, name: 'GreenEnergy – B2B', channel: 'LinkedIn', budget: 4000, status: 'active', lastModified: '30.1.2026' },
        { id: 8, name: 'TravelAgency – Summer', channel: 'Google', budget: 6000, status: 'active', lastModified: '29.1.2026' },
        { id: 9, name: 'AutoPlus – New Model', channel: 'Google', budget: 7500, status: 'draft', lastModified: '31.1.2026' },
        { id: 10, name: 'EduPlatform – Webinar', channel: 'Meta', budget: 1800, status: 'active', lastModified: '1.2.2026' },
        { id: 11, name: 'BuildCorp – Lead Gen', channel: 'Google', budget: 2200, status: 'draft', lastModified: '28.1.2026' },
        { id: 12, name: 'FoodDelivery – App Install', channel: 'Meta', budget: 4500, status: 'active', lastModified: '30.1.2026' },
      ],
      tasks: [
        { id: 1, title: 'Pripremiti pitch za Digital d.o.o.', column: 'todo' },
        { id: 2, title: 'Revizija kreativa – Brand Co', column: 'in_progress' },
        { id: 3, title: 'Mjesečni izvještaj E-commerce HR', column: 'done' },
        { id: 4, title: 'A/B test naslova – Fashion', column: 'todo' },
        { id: 5, title: 'Setup LinkedIn kampanja – Tech Startup', column: 'in_progress' },
        { id: 6, title: 'Kopija za Restaurant Group oglase', column: 'todo' },
        { id: 7, title: 'Analiza CPA – GreenEnergy', column: 'done' },
        { id: 8, title: 'Landing page optimizacija – TravelAgency', column: 'in_progress' },
        { id: 9, title: 'Kreative za AutoPlus Q2', column: 'todo' },
        { id: 10, title: 'Kick-off sastanak EduPlatform', column: 'done' },
        { id: 11, title: 'SEO audit – BuildCorp', column: 'todo' },
        { id: 12, title: 'Podsjetnik za odobrenje – MedLab', column: 'in_progress' },
        { id: 13, title: 'Tjedni izvještaj klijentima', column: 'todo' },
        { id: 14, title: 'Sync leadova u CRM', column: 'done' },
        { id: 15, title: 'Tagiranje kampanja po performansama', column: 'in_progress' },
      ],
      approvals: [
        { id: 1, clientName: 'Brand Co', type: 'creative', assetName: 'Banner set Q1', status: 'pending' },
        { id: 2, clientName: 'E-commerce HR', type: 'copy', assetName: 'Landing headline A/B', status: 'pending' },
        { id: 3, clientName: 'AutoPlus', type: 'landing', assetName: 'LP New Model 2026', status: 'pending' },
        { id: 4, clientName: 'Fashion Brand', type: 'creative', assetName: 'Instagram carousel Spring', status: 'pending' },
        { id: 5, clientName: 'Tech Startup', type: 'copy', assetName: 'LinkedIn ad copy set', status: 'pending' },
        { id: 6, clientName: 'TravelAgency', type: 'landing', assetName: 'Summer offer LP', status: 'pending' },
        { id: 7, clientName: 'GreenEnergy', type: 'creative', assetName: 'B2B whitepaper CTA', status: 'pending' },
        { id: 8, clientName: 'Digital d.o.o.', type: 'copy', assetName: 'Product launch email', status: 'pending' },
      ],
      bookings: null,
    },
    odvjetnik: {
      kpis: [
        { value: 14, suffix: '' },
        { value: 9, suffix: '' },
        { value: 5, suffix: '' },
        { value: '4.2h', suffix: '' },
      ],
      inbox: [
        { id: 1, name: 'Ante M.', preview: 'Potreban mi je savjet za raskid ugovora...', time: '10 min', unread: true, tag: 'hitno' },
        { id: 2, name: 'Marija S.', preview: 'Nasljedstvo – što trebam donijeti na konzultaciju?', time: '30 min', unread: true, tag: 'standard' },
        { id: 3, name: 'Igor K.', preview: 'Oštećenje na stanu – tko snosi troškove?', time: '1h', unread: false, tag: 'hitno' },
        { id: 4, name: 'Jelena P.', preview: 'Radni spor – mogu li dobiti termin?', time: '3h', unread: false, tag: 'hitno' },
        { id: 5, name: 'Krešimir L.', preview: 'Osnivanje d.o.o. – koraci i cijena...', time: '1d', unread: true, tag: 'standard' },
        { id: 6, name: 'Sanja D.', preview: 'Razvod – dogovoreni uvjeti...', time: '1d', unread: false, tag: 'standard' },
        { id: 7, name: 'Bruno V.', preview: 'Potraživanje od dužnika...', time: '2d', unread: false, tag: 'hitno' },
        { id: 8, name: 'Tina F.', preview: 'Pregled ugovora prije potpisa...', time: '2d', unread: true, tag: 'standard' },
        { id: 9, name: 'Davor K.', preview: 'Žalba na odluku porezne uprave...', time: '3d', unread: false, tag: 'hitno' },
        { id: 10, name: 'Martina B.', preview: 'Pregled kupoprodajnog ugovora za stan...', time: '3d', unread: true, tag: 'standard' },
        { id: 11, name: 'Tomislav J.', preview: 'Potrebna mi je punomoć za zastupanje...', time: '4d', unread: false, tag: 'standard' },
        { id: 12, name: 'Grad Ploče', preview: 'Natječaj za pravni savjet – javna nabava...', time: '5d', unread: true, tag: 'hitno' },
      ],
      leads: [
        { id: 1, name: 'Ante M.', intent: 'Raskid ugovora', budget: '-', status: 'new' },
        { id: 2, name: 'Marija S.', intent: 'Nasljedstvo', budget: '-', status: 'qualified' },
        { id: 3, name: 'Igor K.', intent: 'Oštećenje stana', budget: '-', status: 'booked' },
        { id: 4, name: 'Jelena P.', intent: 'Radni spor', budget: '-', status: 'new' },
        { id: 5, name: 'Krešimir L.', intent: 'Osnivanje d.o.o.', budget: '-', status: 'qualified' },
        { id: 6, name: 'Sanja D.', intent: 'Razvod', budget: '-', status: 'booked' },
        { id: 7, name: 'Bruno V.', intent: 'Potraživanje', budget: '-', status: 'new' },
        { id: 8, name: 'Tina F.', intent: 'Pregled ugovora', budget: '-', status: 'qualified' },
        { id: 9, name: 'Luka B.', intent: 'Žalba na odluku', budget: '-', status: 'closed' },
      ],
      clients: [
        { id: 1, name: 'Ante Marković', tip: 'fizicka', kontakt: 'ante@email.hr', status: 'aktivan' },
        { id: 2, name: 'Marija Šimić', tip: 'fizicka', kontakt: 'marija.s@email.hr', status: 'aktivan' },
        { id: 3, name: 'Igor Kovač', tip: 'fizicka', kontakt: 'igor.k@gmail.com', status: 'aktivan' },
        { id: 4, name: 'Jelena Perić', tip: 'fizicka', kontakt: '+385 91 123 4567', status: 'aktivan' },
        { id: 5, name: 'TechVision d.o.o.', tip: 'pravna', kontakt: 'info@techvision.hr', status: 'aktivan' },
        { id: 6, name: 'Sanja Dragić', tip: 'fizicka', kontakt: 'sanja.d@email.hr', status: 'aktivan' },
        { id: 7, name: 'Bruno Vuković', tip: 'fizicka', kontakt: 'bruno.v@gmail.com', status: 'aktivan' },
        { id: 8, name: 'Tina Franić', tip: 'fizicka', kontakt: '+385 98 765 4321', status: 'aktivan' },
        { id: 9, name: 'Luka Belić', tip: 'fizicka', kontakt: 'luka.b@email.hr', status: 'neaktivan' },
        { id: 10, name: 'Invest Group j.d.o.o.', tip: 'pravna', kontakt: 'legal@investgroup.hr', status: 'aktivan' },
        { id: 11, name: 'Davor Kralj', tip: 'fizicka', kontakt: 'davor.k@email.hr', status: 'aktivan' },
        { id: 12, name: 'Martina Babić', tip: 'fizicka', kontakt: 'martina.b@gmail.com', status: 'aktivan' },
      ],
      cases: [
        { id: 1, vrsta: 'ugovorno', faza: 'active', prioritet: 'visok', klijentId: 1, klijent: 'Ante Marković', zadnjaAktivnost: '28.1.2026' },
        { id: 2, vrsta: 'nasljedstvo', faza: 'active', prioritet: 'srednji', klijentId: 2, klijent: 'Marija Šimić', zadnjaAktivnost: '29.1.2026' },
        { id: 3, vrsta: 'imovinsko', faza: 'waiting', prioritet: 'visok', klijentId: 3, klijent: 'Igor Kovač', zadnjaAktivnost: '27.1.2026' },
        { id: 4, vrsta: 'radno', faza: 'new', prioritet: 'hitno', klijentId: 4, klijent: 'Jelena Perić', zadnjaAktivnost: '30.1.2026' },
        { id: 5, vrsta: 'tvrrtko', faza: 'active', prioritet: 'srednji', klijentId: 5, klijent: 'TechVision d.o.o.', zadnjaAktivnost: '29.1.2026' },
        { id: 6, vrsta: 'obiteljsko', faza: 'active', prioritet: 'srednji', klijentId: 6, klijent: 'Sanja Dragić', zadnjaAktivnost: '28.1.2026' },
        { id: 7, vrsta: 'potrazivanje', faza: 'waiting', prioritet: 'visok', klijentId: 7, klijent: 'Bruno Vuković', zadnjaAktivnost: '26.1.2026' },
        { id: 8, vrsta: 'ugovorno', faza: 'active', prioritet: 'srednji', klijentId: 8, klijent: 'Tina Franić', zadnjaAktivnost: '30.1.2026' },
        { id: 9, vrsta: 'upravno', faza: 'closed', prioritet: 'srednji', klijentId: 9, klijent: 'Luka Belić', zadnjaAktivnost: '15.1.2026' },
        { id: 10, vrsta: 'imovinsko', faza: 'new', prioritet: 'srednji', klijentId: 12, klijent: 'Martina Babić', zadnjaAktivnost: '31.1.2026' },
      ],
      documents: [
        { id: 1, naziv: 'Ugovor o raskidu – Ante M.', tag: 'ugovor', slucajId: 1, slucaj: 'Raskid ugovora', status: 'draft' },
        { id: 2, naziv: 'Zahtjev za nasljedstvo – Marija S.', tag: 'podnesak', slucajId: 2, slucaj: 'Nasljedstvo', status: 'sent' },
        { id: 3, naziv: 'Tužba – oštećenje stana', tag: 'podnesak', slucajId: 3, slucaj: 'Oštećenje stana', status: 'draft' },
        { id: 4, naziv: 'Punomoć – Jelena P.', tag: 'punomoc', slucajId: 4, slucaj: 'Radni spor', status: 'signed' },
        { id: 5, naziv: 'Osvježenje d.o.o. – osnivački ugovor', tag: 'ugovor', slucajId: 5, slucaj: 'Osnivanje d.o.o.', status: 'draft' },
        { id: 6, naziv: 'Sporazum o razvodu – Sanja D.', tag: 'ugovor', slucajId: 6, slucaj: 'Razvod', status: 'sent' },
        { id: 7, naziv: 'Opoziv – potraživanje Bruno V.', tag: 'podnesak', slucajId: 7, slucaj: 'Potraživanje', status: 'draft' },
        { id: 8, naziv: 'Ugovor o kupoprodaji – Tina F.', tag: 'ugovor', slucajId: 8, slucaj: 'Pregled ugovora', status: 'signed' },
        { id: 9, naziv: 'Žalba – Luka B.', tag: 'podnesak', slucajId: 9, slucaj: 'Žalba na odluku', status: 'sent' },
        { id: 10, naziv: 'Punomoć za zastupanje – Martina B.', tag: 'punomoc', slucajId: 10, slucaj: 'Kupoprodaja stana', status: 'draft' },
        { id: 11, naziv: 'Naknada štete – Igor K.', tag: 'podnesak', slucajId: 3, slucaj: 'Oštećenje stana', status: 'draft' },
        { id: 12, naziv: 'Ugovor o angažmanu – TechVision', tag: 'ugovor', slucajId: 5, slucaj: 'Osnivanje d.o.o.', status: 'sent' },
      ],
      deadlines: [
        { id: 1, datum: '3.2.2026', slucajId: 1, slucaj: 'Raskid ugovora', zadatak: 'Rok za odgovor tuženiku', dodijeljeno: 'Odvjetnik', status: 'pending' },
        { id: 2, datum: '5.2.2026', slucajId: 2, slucaj: 'Nasljedstvo', zadatak: 'Predaja dokumentacije na sud', dodijeljeno: 'Odvjetnik', status: 'pending' },
        { id: 3, datum: '7.2.2026', slucajId: 4, slucaj: 'Radni spor', zadatak: 'Rok žalbe na odluku', dodijeljeno: 'Odvjetnik', status: 'pending' },
        { id: 4, datum: '10.2.2026', slucajId: 3, slucaj: 'Oštećenje stana', zadatak: 'Podsjetnik – čekanje odgovora suda', dodijeljeno: 'Paralegal', status: 'pending' },
        { id: 5, datum: '12.2.2026', slucajId: 5, slucaj: 'Osnivanje d.o.o.', zadatak: 'Registracija u sudski register', dodijeljeno: 'Odvjetnik', status: 'pending' },
        { id: 6, datum: '15.2.2026', slucajId: 6, slucaj: 'Razvod', zadatak: 'Rok za predaju sporazuma', dodijeljeno: 'Odvjetnik', status: 'pending' },
        { id: 7, datum: '18.2.2026', slucajId: 7, slucaj: 'Potraživanje', zadatak: 'Podsjetnik – sljedeći korak', dodijeljeno: 'Paralegal', status: 'pending' },
        { id: 8, datum: '20.2.2026', slucajId: 8, slucaj: 'Pregled ugovora', zadatak: 'Potvrda potpisa – Tina F.', dodijeljeno: 'Odvjetnik', status: 'pending' },
        { id: 9, datum: '25.2.2026', slucajId: 10, slucaj: 'Kupoprodaja stana', zadatak: 'Pregled nacrta – Martina B.', dodijeljeno: 'Paralegal', status: 'pending' },
        { id: 10, datum: '28.2.2026', slucajId: 1, slucaj: 'Raskid ugovora', zadatak: 'Završna konzultacija', dodijeljeno: 'Odvjetnik', status: 'pending' },
      ],
      bookings: null,
    },
    ordinacija: {
      kpis: [
        { value: 42, suffix: '' },
        { value: 28, suffix: '' },
        { value: 8, suffix: '%' },
        { value: 82, suffix: '%' },
      ],
      inbox: [
        { id: 1, name: 'Patient M.K.', preview: 'Mogu li dobiti termin za pregled očiju?', time: '8 min', unread: true },
        { id: 2, name: 'Patient A.J.', preview: 'Treba mi potvrda za poslodavca...', time: '25 min', unread: true },
        { id: 3, name: 'Patient P.Š.', preview: 'Pitanje o pripremi za nalaz krvi...', time: '1h', unread: false },
        { id: 4, name: 'Patient I.V.', preview: 'Želim promijeniti termin na petak.', time: '2h', unread: true },
        { id: 5, name: 'Patient T.L.', preview: 'Ima li hitni termin sutra?', time: '5h', unread: false },
        { id: 6, name: 'Patient N.B.', preview: 'Ponovna narudžba za 3 tjedna...', time: '1d', unread: false },
        { id: 7, name: 'Patient M.R.', preview: 'Cijena preventivnog pregleda?', time: '1d', unread: true },
        { id: 8, name: 'Patient K.S.', preview: 'Rezultati nalaza – kada stižu?', time: '2d', unread: false },
      ],
      leads: [
        { id: 1, name: 'Patient M.K.', intent: 'Pregled očiju', budget: '-', status: 'booked' },
        { id: 2, name: 'Patient A.J.', intent: 'Potvrda za poslodavca', budget: '-', status: 'qualified' },
        { id: 3, name: 'Patient I.V.', intent: 'Promjena termina', budget: '-', status: 'new' },
        { id: 4, name: 'Patient T.L.', intent: 'Hitni termin', budget: '-', status: 'qualified' },
      ],
      triage: [
        { id: 1, patient: 'Ana K.', symptoms: 'Bol u grlu, povišena temp. 2 dana', urgency: 'medium', recommendation: 'Pregled u ordinaciji u 24–48h', status: 'pending' },
        { id: 2, patient: 'Marko P.', symptoms: 'Oteklina oka, crvenilo', urgency: 'high', recommendation: 'Hitni pregled danas', status: 'pending' },
        { id: 3, patient: 'Petra Š.', symptoms: 'Priprema za nalaz krvi – pitanja', urgency: 'low', recommendation: 'Pošalji upute za pripremu', status: 'pending' },
        { id: 4, patient: 'Ivan V.', symptoms: 'Kontrola krvnog tlaka, 3 mj. od zadnjeg', urgency: 'low', recommendation: 'Zakaži redovnu kontrolu', status: 'pending' },
        { id: 5, patient: 'Maja L.', symptoms: 'Uporna glavobolja 5 dana', urgency: 'medium', recommendation: 'Pregled u roku 48h', status: 'pending' },
        { id: 6, patient: 'Tomislav B.', symptoms: 'Ponovna recept za kroničnu terapiju', urgency: 'low', recommendation: 'Upute za e-recept ili dolazak', status: 'contacted' },
        { id: 7, patient: 'Lucija M.', symptoms: 'Povreda koljena pri sportu', urgency: 'high', recommendation: 'Hitni pregled + eventualno slikanje', status: 'pending' },
        { id: 8, patient: 'Filip R.', symptoms: 'Prehlada, kašalj 1 tjedan', urgency: 'low', recommendation: 'Savjet ili kratki pregled', status: 'pending' },
        { id: 9, patient: 'Sandra K.', symptoms: 'Pregled za posao – potvrda', urgency: 'low', recommendation: 'Zakaži pregled', status: 'pending' },
        { id: 10, patient: 'Bruno J.', symptoms: 'Nesanica, umor – trajanje 2 tjedna', urgency: 'medium', recommendation: 'Pregled + anamneza', status: 'pending' },
        { id: 11, patient: 'Elena T.', symptoms: 'Osip na koži, svrbež', urgency: 'medium', recommendation: 'Pregled u 24–48h', status: 'pending' },
        { id: 12, patient: 'Davor S.', symptoms: 'Ponovna narudžba za 3 tjedna', urgency: 'low', recommendation: 'Zakaži termin', status: 'pending' },
      ],
      appointments: [
        { id: 1, patientId: 1, client: 'Patient M.K.', service: 'Pregled očiju', date: '5.2.2026', dateLabel: 'Srijeda 5.2.', time: '09:00', status: 'confirmed' },
        { id: 2, patientId: 2, client: 'Patient P.Š.', service: 'Nalaz krvi', date: '6.2.2026', dateLabel: 'Četvrtak 6.2.', time: '08:30', status: 'confirmed' },
        { id: 3, patientId: 3, client: 'Patient I.V.', service: 'Kontrola', date: '7.2.2026', dateLabel: 'Petak 7.2.', time: '14:00', status: 'booked' },
        { id: 4, patientId: 4, client: 'Patient N.B.', service: 'Ponovna narudžba', date: '10.2.2026', dateLabel: 'Ponedjeljak 10.2.', time: '10:00', status: 'booked' },
        { id: 5, patientId: 5, client: 'Patient K.S.', service: 'Pregled', date: '4.2.2026', dateLabel: 'Utorak 4.2.', time: '11:00', status: 'cancelled' },
        { id: 6, patientId: 6, client: 'Ana K.', service: 'Pregled', date: '5.2.2026', dateLabel: 'Srijeda 5.2.', time: '10:30', status: 'booked' },
        { id: 7, patientId: 7, client: 'Marko P.', service: 'Hitni pregled', date: '5.2.2026', dateLabel: 'Srijeda 5.2.', time: '11:00', status: 'completed' },
        { id: 8, patientId: 8, client: 'Petra Š.', service: 'Kontrola', date: '6.2.2026', dateLabel: 'Četvrtak 6.2.', time: '09:00', status: 'confirmed' },
        { id: 9, patientId: 9, client: 'Ivan V.', service: 'Kontrola tlaka', date: '6.2.2026', dateLabel: 'Četvrtak 6.2.', time: '15:00', status: 'booked' },
        { id: 10, patientId: 10, client: 'Maja L.', service: 'Pregled', date: '7.2.2026', dateLabel: 'Petak 7.2.', time: '09:30', status: 'noshow' },
        { id: 11, patientId: 11, client: 'Tomislav B.', service: 'Kontrola', date: '7.2.2026', dateLabel: 'Petak 7.2.', time: '14:00', status: 'completed' },
        { id: 12, patientId: 12, client: 'Lucija M.', service: 'Pregled', date: '8.2.2026', dateLabel: 'Subota 8.2.', time: '10:00', status: 'booked' },
        { id: 13, patientId: 13, client: 'Filip R.', service: 'Pregled', date: '8.2.2026', dateLabel: 'Subota 8.2.', time: '11:30', status: 'confirmed' },
        { id: 14, patientId: 14, client: 'Sandra K.', service: 'Pregled za posao', date: '9.2.2026', dateLabel: 'Nedjelja 9.2.', time: '08:00', status: 'booked' },
        { id: 15, patientId: 15, client: 'Bruno J.', service: 'Kontrola', date: '10.2.2026', dateLabel: 'Ponedjeljak 10.2.', time: '16:00', status: 'booked' },
        { id: 16, patientId: 16, client: 'Elena T.', service: 'Pregled', date: '11.2.2026', dateLabel: 'Utorak 11.2.', time: '09:00', status: 'confirmed' },
      ],
      patients: [
        { id: 1, name: 'Patient M.K.', lastVisit: '28.1.2026', visitCount: 8, notes: '', history: [] },
        { id: 2, name: 'Patient A.J.', lastVisit: '20.1.2026', visitCount: 3, notes: '', history: [] },
        { id: 3, name: 'Patient P.Š.', lastVisit: '15.1.2026', visitCount: 5, notes: '', history: [] },
        { id: 4, name: 'Patient I.V.', lastVisit: '10.1.2026', visitCount: 12, notes: '', history: [] },
        { id: 5, name: 'Patient T.L.', lastVisit: null, visitCount: 0, notes: '', history: [] },
        { id: 6, name: 'Ana K.', lastVisit: '2.2.2026', visitCount: 4, notes: '', history: [] },
        { id: 7, name: 'Marko P.', lastVisit: '5.2.2026', visitCount: 1, notes: '', history: [] },
        { id: 8, name: 'Petra Š.', lastVisit: '30.1.2026', visitCount: 6, notes: '', history: [] },
        { id: 9, name: 'Ivan V.', lastVisit: '22.1.2026', visitCount: 9, notes: '', history: [] },
        { id: 10, name: 'Maja L.', lastVisit: '18.1.2026', visitCount: 2, notes: '', history: [] },
        { id: 11, name: 'Tomislav B.', lastVisit: '7.2.2026', visitCount: 14, notes: '', history: [] },
        { id: 12, name: 'Lucija M.', lastVisit: '25.1.2026', visitCount: 3, notes: '', history: [] },
        { id: 13, name: 'Filip R.', lastVisit: '5.1.2026', visitCount: 7, notes: '', history: [] },
        { id: 14, name: 'Sandra K.', lastVisit: null, visitCount: 0, notes: '', history: [] },
        { id: 15, name: 'Bruno J.', lastVisit: '12.1.2026', visitCount: 5, notes: '', history: [] },
        { id: 16, name: 'Elena T.', lastVisit: '29.1.2026', visitCount: 4, notes: '', history: [] },
      ],
      instructions: [
        { id: 1, service: 'Čišćenje', title: 'Priprema za čišćenje zuba', body: 'Do 2 sata prije termina običan obrok. Isperite usta. Ako uzimate lijekove koji utječu na zgrušavanje krvi, obavijestite nas.' },
        { id: 2, service: 'Pregled', title: 'Opći pregled – priprema', body: 'Donesite listu trenutnih lijekova i alergija. Za nalaz krvi dolazak natašte (preporuka 8–12h natašte).' },
        { id: 3, service: 'Zahvat', title: 'Prije manjeg zahvata', body: 'Laki obrok moguć 2h prije. Nosite udobnu odjeću. Ako ste preboljeli infekciju, javite prije termina.' },
        { id: 4, service: 'Nalaz krvi', title: 'Upute za nalaz krvi', body: 'Natašte 8–12 sati (samo voda). Nema teških napora 24h prije. Donesite uputnicu i osobnu iskaznicu.' },
        { id: 5, service: 'Kontrola', title: 'Kontrolni pregled', body: 'Donesite rezultate i listu lijekova ako su se promijenili od zadnjeg pregleda.' },
        { id: 6, service: 'Pregled za posao', title: 'Pregled za poslodavca', body: 'Donesite obrazac od poslodavca i osobnu. Natašte nije obavezno osim ako je navedeno.' },
        { id: 7, service: 'E-recept', title: 'Ponovna narudžba / e-recept', body: 'Možete zatražiti e-recept putem poruke ako je terapija već propisana. Za novu terapiju potreban je pregled.' },
        { id: 8, service: 'Hitni termin', title: 'Hitni termin', body: 'Dođite u ordinaciju u radno vrijeme. Za hitne slučajeve izvan radnog vremena obratite se hitnoj pomoći.' },
      ],
      bookings: null,
    },
  };

  global.DemoMockData = {
    data: data,
    statusKeys: statusKeys,
    getKpiLabels: getKpiLabels,
    getVerticalData: function (vertical) {
      return data[vertical] || data.nekretnine;
    },
  };
})(typeof window !== 'undefined' ? window : this);
